{
 "title": "Opflex endpoints",
 "tags": [ "opflex" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Tx Packets (5min avg pps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Pkts/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_name,namespace) (rate(opflex_endpoint_tx_packets[5m]))",
     "legendFormat": "pod={{exported_name}}, namespace={{namespace}}"
    }
   ]
  },
  {
   "title": "Rx Packets (5min avg pps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Pkts/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_name,namespace) (rate(opflex_endpoint_rx_packets[5m]))"
    }
   ]
  },
  {
   "title": "Tx Dropped Packets (5min avg pps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Pkts/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (name,namespace) (rate(opflex_endpoint_tx_drop_packets[5m]))"
    }
   ]
  },
  {
   "title": "Rx Dropped Packets (5min avg pps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Pkts/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (name,namespace) (rate(opflex_endpoint_rx_drop_packets[5m]))"
    }
   ]
  }
 ]
}