{
 "title": "Opflex Peer Stats",
 "tags": [ "opflex" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Identity Request Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_identity_req_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Identity Response Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_identity_resp_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Identity Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_identity_err_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Resolve Request Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_policy_resolve_req_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Resolve Response Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_policy_resolve_resp_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Resolve Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_policy_resolve_err_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Unresolve Request Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_policy_unresolve_req_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Unresolve Response Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_policy_unresolve_resp_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Unresolve Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_policy_unresolve_err_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "EP Declare Request Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_ep_declare_req_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "EP Declare Response Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_ep_declare_resp_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "EP Declare Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_ep_declare_err_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "EP Undeclare Request Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_ep_undeclare_req_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "EP Undeclare Response Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_ep_undeclare_resp_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "EP Undeclare Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_ep_undeclare_err_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "State Report Request Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_state_report_req_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "State Report Response Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_state_report_resp_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "State Report Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_state_report_err_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Update Receive Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_policy_update_receive_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Unresolved Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_peer_unresolved_policy_count",
     "legendFormat": "peer:{{peer}}, instance:{{instance}}"
    }
   ]
  }
 ]
}