{
 "title": "Opflex Server Stats",
 "tags": [ "opflex" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Identity Request Count",
   "type": "graph",
   "description": "number of identity requests received from an opflex agent",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_identity_req_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Update Count",
   "type": "graph",
   "description": "number of policy updates received from grpc server that are sent to an opflex agent",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_policy_update_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Unavailable Resolve Count",
   "type": "graph",
   "description": "number of unavailable policies on resolves received from an opflex agent",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_policy_unavailable_resolve_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Resolve Count",
   "type": "graph",
   "description": "number of policy resolves received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_policy_resolve_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Resolve Error Count",
   "type": "graph",
   "description": "number of errors on policy resolves received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_policy_resolve_err_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Unresolve Count",
   "type": "graph",
   "description": "number of policy unresolves received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_policy_unresolve_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Unresolve Error Count",
   "type": "graph",
   "description": "number of errors on policy unresolves received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_policy_unresolve_err_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Endpoint Declare Count",
   "type": "graph",
   "description": "number of endpoint declares received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_ep_declare_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Endpoint Declare Error Count",
   "type": "graph",
   "description": "number of errors on endpoint declares received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_ep_declare_err_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Endpoint Undeclare Count",
   "type": "graph",
   "description": "number of endpoint undeclares received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_ep_undeclare_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Endpoint Undeclare Error Count",
   "type": "graph",
   "description": "number of errors on endpoint undeclares received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_ep_undeclare_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Endpoint Resolve Count",
   "type": "graph",
   "description": "number of endpoint resolves received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_ep_resolve_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Endpoint Resolve Error Count",
   "type": "graph",
   "description": "number of errors on endpoint resolves received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_ep_resolve_err_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Endpoint Unresolve Count",
   "type": "graph",
   "description": "number of endpoint unresolve received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_ep_unresolve_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy Endpoint Unresolve Error Count",
   "type": "graph",
   "description": "number of errors on endpoint unresolve received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_ep_unresolve_err_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy State Report Count",
   "type": "graph",
   "description": "number of state reports received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_state_report_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Policy State Report Error Count",
   "type": "graph",
   "description": "number of errors on state reports received from an opflex agent",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opflex_agent_state_report_err_count",
     "legendFormat": "agent:{{agent}}, instance:{{instance}}"
    }
   ]
  }
 ]
}